Repository atlp-rwanda/Avengers-Phantom-BE, pull requests merged in 2022-05, with the labels that each got.

#12 Ft forgot password
  .DS_Store
  .babelrc
  .gitignore
  example.env
  locales/.DS_Store
  migrations/20220423123350-create-roles.js
  migrations/20220424184700-create-bus.js
  migrations/20220429162252-create-user.js
  models/bus.js
  models/index.js
  models/roles.js
  models/user.js
  package-lock.json
  package.json
  seeders/20220419165604-create-fake-users.js
  src/.DS_Store
  src/Authentication/AuthController.js
  src/Buses/controllers/bus.controller.js
  src/Buses/docs/bus.docs.js
  src/Buses/routes/bus.route.js
  src/Middlewares/Middlewares.js
  src/Roles/controllers/roles.controller.js
  src/Route/Routes/route.route.js
  src/Route/controllers/route.controller.js
  src/Route/route.docs.js
  src/Users/Routes/users.route.js
  src/Users/controllers/user.controller.js
  src/utils/Email.js
Labels: Waiting for reviews

#13 ft(password reset):password resetting
  .DS_Store
  models/user.js
  package-lock.json
  src/.DS_Store
  src/Authentication/AuthController.js
  src/Users/Routes/users.route.js
  src/utils/Email.js
Labels: Waiting for reviews

#14 ft(bus assignment):Assign Driver to Bus
  .DS_Store
  Procfile
  app.js
  migrations/20220429162252-create-user.js
  migrations/20220504130137-create-bus.js
  models/bus.js
  models/user.js
  package-lock.json
  package.json
  src/Assignment/controllers/AssignDrivertoBus.controller.js
  src/Assignment/routes/assingDrivertoBus.route.js
  src/Authentication/AuthController.js
  src/Buses/controllers/bus.controller.js
  src/Middlewares/Middlewares.js
  src/Users/Routes/users.route.js
  src/Users/controllers/user.controller.js
Labels: wip, Waiting for reviews

#17 Ft update profile
  src/Users/Routes/users.route.js
  src/Users/controllers/user.controller.js
Labels: Waiting for reviews

#20 ft(backend-deployment):deployed phantom
  .gitignore
  config/config.js
  migrations/20220511141050-create-route.js
  migrations/20220512124800-create-assign-bus-to-route.js
  models/assignbustoroute.js
  models/index.js
  models/route.js
  package-lock.json
  package.json
  server.js
  src/Assignment/BusToRoutes/Routes/AssignmentRoutes.js
  src/Assignment/BusToRoutes/controllers/assignBusToRouteController.js
  src/Authentication/AuthController.js
Labels: Waiting for reviews, deployment

#21 ft(roles):user roles
  migrations/20220423123350-create-roles.js
  migrations/20220429162252-create-user.js
  migrations/20220517091100-create-role.js
  models/role.js
  models/user.js
  package.json
  src/Authentication/AuthController.js
  src/Roles/Routes/roles.route.js
  src/Roles/controllers/roles.controller.js
  src/Users/Routes/users.route.js
  src/Users/controllers/user.controller.js
Labels: wip, Waiting for reviews

#19 Ft register and signin tests
  .github/workflows/phantom.yml
  package-lock.json
  package.json
  src/docs/test/app.test.js
Labels: wip

#22 ft(Testing bus):Bus CRUD Operations tests
  package-lock.json
  package.json
  src/Authentication/AuthController.js
  src/Buses/controllers/bus.controller.js
  src/Middlewares/Middlewares.js
  src/Roles/controllers/roles.controller.js
  src/Users/Routes/users.route.js
  src/Users/controllers/user.controller.js
  src/docs/test/bus.test.js
Labels: wip, Waiting for reviews

#23 ft(Role tests): testing roles
  package-lock.json
  src/docs/test/bus.test.js
  src/docs/test/role.test.js
Labels: wip, Waiting for reviews

#25 bg(reset token generation)
  src/Authentication/AuthController.js
  src/utils/GenerateToken.js
Labels: Done
